## 0. Load the data

In [1]:
# imports:
import pandas as pd
import matplotlib.pyplot as plt
import os

PREFIX_PATH = '/home/sramkova/diploma_thesis_data/cicids2017/attacks'
PREFIX_PATH = PREFIX_PATH + '/' + '/'.join(os.getcwd().split('/')[-2:]) + '/'
INPUT_CSV = PREFIX_PATH + 'query_output_processing.csv'
print(INPUT_CSV)


raw_data = pd.read_csv(INPUT_CSV)

# check that all columns are correctly loaded
raw_data.head()

/home/sramkova/diploma_thesis_data/cicids2017/attacks/2_thursday/web_attack_xss/query_output_processing.csv

,originated_ip,uid,connection.uid,connection.conn_state,connection.duration,connection.orig_bytes,connection.orig_ip_bytes,connection.orig_p,connection.orig_pkts,connection.proto,...,resp_resp_similar_http_status_code_count,resp_resp_similar_http_user_agent_count,resp_resp_similar_ssl_version_count,resp_resp_similar_ssl_cipher_count,resp_resp_similar_ssl_curve_count,resp_resp_similar_ssl_validation_status_count,resp_resp_similar_files_source_count,resp_resp_similar_file_md5_count,attacker_label,victim_label
0,192.168.10.25,0x99,ChFW9X31rgQuPcZklh,SF,0.144792,1397,1901,49180,12,tcp,...,0,0,0,0,0,0,0,0,No,No
1,192.168.10.25,0xc3,CGXL9o4dBJDT4WfRi,SF,30.729384,2084,2980,49186,17,tcp,...,0,0,0,0,0,0,0,0,No,No
2,192.168.10.25,0xf1,CskeJZ3qePKwfJ1YAl,SHR,0.000003,0,0,49184,0,udp,...,0,0,0,0,0,0,0,0,No,Yes
3,192.168.10.25,0x145,C9uQO31v3ZSeHD2pLg,SF,0.000115,188,244,49168,2,udp,...,0,0,0,0,0,0,0,0,No,No
4,192.168.10.25,0x22a,ChFVpJ1gniKec3d7tg,SF,0.001121,76,132,53678,2,udp,...,0,0,0,0,0,0,0,0,No,No

In [2]:
pd.set_option('display.max_rows', None)
raw_data.dtypes

originated_ip                                     object
uid                                               object
connection.uid                                    object
connection.conn_state                             object
connection.duration                              float64
connection.orig_bytes                              int64
connection.orig_ip_bytes                           int64
connection.orig_p                                  int64
connection.orig_pkts                               int64
connection.proto                                  object
connection.resp_bytes                              int64
connection.resp_ip_bytes                           int64
connection.resp_p                                  int64
connection.resp_pkts                               int64
connection.service                                object
connection.ts                                     object
responded_ip                                      object
dns_count                                          int64
ssh_count                                          int64
http_count                                         int64
ssl_count                                          int64
files_count                                        int64
dns_qtype                                         object
dns_rcode                                         object
ssh_auth_attempts                                 object
ssh_host_key                                      object
http_method                                       object
http_status_code                                  object
http_user_agent                                   object
ssl_version                                       object
ssl_cipher                                        object
ssl_curve                                         object
ssl_validation_status                             object
files_source                                      object
file_md5                                          object
dns_dicts                                         object
ssh_dicts                                         object
http_dicts                                        object
ssl_dicts                                         object
files_dicts                                       object
connection.time                                   object
orig_orig_total                                    int64
orig_orig_proto_tcp_count                          int64
orig_orig_proto_udp_count                          int64
orig_orig_proto_icmp_count                         int64
orig_orig_connection.protocol_mode                object
orig_orig_connection.service_mode                 object
orig_orig_connection.conn_state_mode              object
orig_orig_connection.time_mean                    object
orig_orig_connection.duration_mean               float64
orig_orig_connection.orig_bytes_mean             float64
orig_orig_connection.orig_pkts_mean              float64
orig_orig_connection.resp_bytes_mean             float64
orig_orig_connection.resp_pkts_mean              float64
orig_orig_orig_p_well_known_count                  int64
orig_orig_orig_p_reg_or_dyn_count                  int64
orig_orig_resp_p_21_count                          int64
orig_orig_resp_p_22_count                          int64
orig_orig_resp_p_53_count                          int64
orig_orig_resp_p_80_count                          int64
orig_orig_resp_p_123_count                         int64
orig_orig_resp_p_443_count                         int64
orig_orig_resp_p_3389_count                        int64
orig_orig_resp_p_well_known_count                  int64
orig_orig_resp_p_reg_count                         int64
orig_orig_resp_p_dyn_count                         int64
orig_orig_dns_count_mean                         float64
orig_orig_ssh_count_mean                         float64
orig_orig_http_count_mean                        float64
orig_orig_ssl_count_mean                         float64
orig_orig_files_count_mean                       float64
orig_orig_similar_conns_count                      int64
orig_orig_similar_dns_qtype_count                  int64
orig_orig_similar_dns_rcode_count                  int64
orig_orig_similar_ssh_auth_attempts_count          int64
orig_orig_similar_ssh_host_key_count               int64
orig_orig_similar_http_method_count                int64
orig_orig_similar_http_status_code_count           int64
orig_orig_similar_http_user_agent_count            int64
orig_orig_similar_ssl_version_count                int64
orig_orig_similar_ssl_cipher_count                 int64
orig_orig_similar_ssl_curve_count                  int64
orig_orig_similar_ssl_validation_status_count      int64
orig_orig_similar_files_source_count               int64
orig_orig_similar_file_md5_count                   int64
orig_resp_total                                    int64
orig_resp_proto_tcp_count                          int64
orig_resp_proto_udp_count                          int64
orig_resp_proto_icmp_count                         int64
orig_resp_connection.protocol_mode                object
orig_resp_connection.service_mode                 object
orig_resp_connection.conn_state_mode              object
orig_resp_connection.time_mean                    object
orig_resp_connection.duration_mean               float64
orig_resp_connection.orig_bytes_mean             float64
orig_resp_connection.orig_pkts_mean              float64
orig_resp_connection.resp_bytes_mean             float64
orig_resp_connection.resp_pkts_mean              float64
orig_resp_orig_p_well_known_count                  int64
orig_resp_orig_p_reg_or_dyn_count                  int64
orig_resp_resp_p_21_count                          int64
orig_resp_resp_p_22_count                          int64
orig_resp_resp_p_53_count                          int64
orig_resp_resp_p_80_count                          int64
orig_resp_resp_p_123_count                         int64
orig_resp_resp_p_443_count                         int64
orig_resp_resp_p_3389_count                        int64
orig_resp_resp_p_well_known_count                  int64
orig_resp_resp_p_reg_count                         int64
orig_resp_resp_p_dyn_count                         int64
orig_resp_dns_count_mean                         float64
orig_resp_ssh_count_mean                         float64
orig_resp_http_count_mean                        float64
orig_resp_ssl_count_mean                         float64
orig_resp_files_count_mean                       float64
orig_resp_similar_conns_count                      int64
orig_resp_similar_dns_qtype_count                  int64
orig_resp_similar_dns_rcode_count                  int64
orig_resp_similar_ssh_auth_attempts_count          int64
orig_resp_similar_ssh_host_key_count               int64
orig_resp_similar_http_method_count                int64
orig_resp_similar_http_status_code_count           int64
orig_resp_similar_http_user_agent_count            int64
orig_resp_similar_ssl_version_count                int64
orig_resp_similar_ssl_cipher_count                 int64
orig_resp_similar_ssl_curve_count                  int64
orig_resp_similar_ssl_validation_status_count      int64
orig_resp_similar_files_source_count               int64
orig_resp_similar_file_md5_count                   int64
resp_orig_total                                    int64
resp_orig_proto_tcp_count                          int64
resp_orig_proto_udp_count                          int64
resp_orig_proto_icmp_count                         int64
resp_orig_connection.protocol_mode                object
resp_orig_connection.service_mode                 object
resp_orig_connection.conn_state_mode              object
resp_orig_connection.time_mean                    object
resp_orig_connection.duration_mean               float64
resp_orig_connection.orig_bytes_mean             float64
resp_orig_connection.orig_pkts_mean              float64
resp_orig_connection.resp_bytes_mean             float64
resp_orig_connection.resp_pkts_mean              float64
resp_orig_orig_p_well_known_count                  int64
resp_orig_orig_p_reg_or_dyn_count                  int64
resp_orig_resp_p_21_count                          int64
resp_orig_resp_p_22_count                          int64
resp_orig_resp_p_53_count                          int64
resp_orig_resp_p_80_count                          int64
resp_orig_resp_p_123_count                         int64
resp_orig_resp_p_443_count                         int64
resp_orig_resp_p_3389_count                        int64
resp_orig_resp_p_well_known_count                  int64
resp_orig_resp_p_reg_count                         int64
resp_orig_resp_p_dyn_count                         int64
resp_orig_dns_count_mean                         float64
resp_orig_ssh_count_mean                         float64
resp_orig_http_count_mean                        float64
resp_orig_ssl_count_mean                         float64
resp_orig_files_count_mean                       float64
resp_orig_similar_conns_count                      int64
resp_orig_similar_dns_qtype_count                  int64
resp_orig_similar_dns_rcode_count                  int64
resp_orig_similar_ssh_auth_attempts_count          int64
resp_orig_similar_ssh_host_key_count               int64
resp_orig_similar_http_method_count                int64
resp_orig_similar_http_status_code_count           int64
resp_orig_similar_http_user_agent_count            int64
resp_orig_similar_ssl_version_count                int64
resp_orig_similar_ssl_cipher_count                 int64
resp_orig_similar_ssl_curve_count                  int64
resp_orig_similar_ssl_validation_status_count      int64
resp_orig_similar_files_source_count               int64
resp_orig_similar_file_md5_count                   int64
resp_resp_total                                    int64
resp_resp_proto_tcp_count                          int64
resp_resp_proto_udp_count                          int64
resp_resp_proto_icmp_count                         int64
resp_resp_connection.protocol_mode                object
resp_resp_connection.service_mode                 object
resp_resp_connection.conn_state_mode              object
resp_resp_connection.time_mean                    object
resp_resp_connection.duration_mean               float64
resp_resp_connection.orig_bytes_mean             float64
resp_resp_connection.orig_pkts_mean              float64
resp_resp_connection.resp_bytes_mean             float64
resp_resp_connection.resp_pkts_mean              float64
resp_resp_orig_p_well_known_count                  int64
resp_resp_orig_p_reg_or_dyn_count                  int64
resp_resp_resp_p_21_count                          int64
resp_resp_resp_p_22_count                          int64
resp_resp_resp_p_53_count                          int64
resp_resp_resp_p_80_count                          int64
resp_resp_resp_p_123_count                         int64
resp_resp_resp_p_443_count                         int64
resp_resp_resp_p_3389_count                        int64
resp_resp_resp_p_well_known_count                  int64
resp_resp_resp_p_reg_count                         int64
resp_resp_resp_p_dyn_count                         int64
resp_resp_dns_count_mean                         float64
resp_resp_ssh_count_mean                         float64
resp_resp_http_count_mean                        float64
resp_resp_ssl_count_mean                         float64
resp_resp_files_count_mean                       float64
resp_resp_similar_conns_count                      int64
resp_resp_similar_dns_qtype_count                  int64
resp_resp_similar_dns_rcode_count                  int64
resp_resp_similar_ssh_auth_attempts_count          int64
resp_resp_similar_ssh_host_key_count               int64
resp_resp_similar_http_method_count                int64
resp_resp_similar_http_status_code_count           int64
resp_resp_similar_http_user_agent_count            int64
resp_resp_similar_ssl_version_count                int64
resp_resp_similar_ssl_cipher_count                 int64
resp_resp_similar_ssl_curve_count                  int64
resp_resp_similar_ssl_validation_status_count      int64
resp_resp_similar_files_source_count               int64
resp_resp_similar_file_md5_count                   int64
attacker_label                                    object
victim_label                                      object
dtype: object

In [3]:
pd.set_option('display.max_rows', 10)

In [4]:
# select only original connection columns (no neighbourhood):

raw_data = raw_data[['originated_ip', 
                     'responded_ip', 
                     'connection.uid', 
                     'connection.ts', 
                     'connection.resp_pkts', 
                     'connection.resp_ip_bytes', 
                     'connection.orig_p', 
                     'connection.duration',
                     'connection.resp_bytes',
                     'connection.orig_pkts',
                     'connection.proto',
                     'connection.service', 
                     'connection.orig_bytes',
                     'connection.conn_state',
                     'connection.resp_p',
                     'connection.orig_ip_bytes',
                     'dns_count',
                     'ssh_count', 
                     'http_count',
                     'ssl_count',
                     'files_count',
                    ]]
raw_data.head()

,originated_ip,responded_ip,connection.uid,connection.ts,connection.resp_pkts,connection.resp_ip_bytes,connection.orig_p,connection.duration,connection.resp_bytes,connection.orig_pkts,...,connection.service,connection.orig_bytes,connection.conn_state,connection.resp_p,connection.orig_ip_bytes,dns_count,ssh_count,http_count,ssl_count,files_count
0,192.168.10.25,72.5.205.22,ChFW9X31rgQuPcZklh,2017-07-06T12:06:35.060859Z,9,3694,49180,0.144792,3322,12,...,ssl,1397,SF,443,1901,0,0,0,1,2
1,192.168.10.25,216.58.219.205,CGXL9o4dBJDT4WfRi,2017-07-06T12:06:37.071614Z,12,4812,49186,30.729384,4180,17,...,ssl,2084,SF,443,2980,0,0,0,1,3
2,192.168.10.25,192.168.10.50,CskeJZ3qePKwfJ1YAl,2017-07-06T12:05:16.358339Z,2,180,49184,0.000003,124,0,...,dns,0,SHR,137,0,1,0,0,0,0
3,192.168.10.25,192.168.10.3,C9uQO31v3ZSeHD2pLg,2017-07-06T12:04:38.814779Z,2,382,49168,0.000115,326,2,...,none,188,SF,389,244,0,0,0,0,0
4,192.168.10.25,192.168.10.3,ChFVpJ1gniKec3d7tg,2017-07-06T12:06:35.056945Z,2,540,53678,0.001121,484,2,...,dns,76,SF,53,132,1,0,0,0,0

# 1. Get to know the data

### 1.0 Basic statistics

In [5]:
# types and number of non-null values in columns:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21876 entries, 0 to 21875
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   originated_ip             21876 non-null  object
 1   responded_ip              21876 non-null  object
 2   connection.uid            21876 non-null  object
 3   connection.ts             21876 non-null  object
 4   connection.resp_pkts      21876 non-null  int64
 5   connection.resp_ip_bytes  21876 non-null  int64
 6   connection.orig_p         21876 non-null  int64
 7   connection.duration       21876 non-null  float64
 8   connection.resp_bytes     21876 non-null  int64
 9   connection.orig_pkts      21876 non-null  int64
 10  connection.proto          21876 non-null  object
 11  connection.service        21876 non-null  object
 12  connection.orig_bytes     21876 non-null  int64
 13  connection.conn_state     21876 non-null  object
 14  connection.resp_p         21876 non-null  int64
 15  connection.orig_ip_bytes  21876 non-null  int64
 16  dns_count                 21876 non-null  int64
 17  ssh_count                 21876 non-null  int64
 18  http_count                21876 non-null  int64
 19  ssl_count                 21876 non-null  int64
 20  files_count               21876 non-null  int64
dtypes: float64(1), int64(13), object(7)
memory usage: 3.5+ MB

In [6]:
# simple statistics of numerical attributes: 
raw_data.describe()

,connection.resp_pkts,connection.resp_ip_bytes,connection.orig_p,connection.duration,connection.resp_bytes,connection.orig_pkts,connection.orig_bytes,connection.resp_p,connection.orig_ip_bytes,dns_count,ssh_count,http_count,ssl_count,files_count
count,2.187600e+04,2.187600e+04,21876.000000,21876.000000,2.187600e+04,2.187600e+04,21876.000000,21876.000000,2.187600e+04,21876.000000,21876.000000,21876.000000,21876.000000,21876.00000
mean,7.547312e+01,1.573343e+05,46550.968550,14.418953,1.542137e+05,5.779964e+01,587.893811,234.507223,3.023709e+03,0.640976,0.001554,0.079219,0.130234,0.37036
std,9.522630e+03,2.113046e+07,19584.107175,50.201217,2.074946e+07,7.053000e+03,3830.995873,2049.949021,2.900084e+05,0.479725,0.039394,0.270087,0.336568,2.28413
min,0.000000e+00,0.000000e+00,3.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.00000
25%,1.000000e+00,1.520000e+02,44377.000000,0.000328,1.060000e+02,1.000000e+00,53.000000,53.000000,9.800000e+01,0.000000,0.000000,0.000000,0.000000,0.00000
50%,2.000000e+00,2.380000e+02,52424.000000,0.038096,1.820000e+02,2.000000e+00,76.000000,53.000000,1.360000e+02,1.000000,0.000000,0.000000,0.000000,0.00000
75%,2.000000e+00,4.720000e+02,60605.000000,0.407965,3.500000e+02,4.000000e+00,183.250000,80.000000,3.160000e+02,1.000000,0.000000,0.000000,0.000000,0.00000
max,1.407985e+06,3.124255e+09,65533.000000,1296.738136,3.067928e+09,1.042889e+06,223623.000000,65529.000000,4.287491e+07,1.000000,1.000000,1.000000,1.000000,76.00000

In [7]:
# source: https://www.geeksforgeeks.org/python-pandas-dataframe-describe-method/

# remove null values to avoid errors  
nonnull_data = raw_data.dropna()  
  
# percentile list 
perc =[.20, .40, .60, .80] 
  
# list of dtypes to include 
include =['object', 'float', 'int'] 
  
# calling describe method 
nonnull_data.describe(percentiles = perc, include = include)

,originated_ip,responded_ip,connection.uid,connection.ts,connection.resp_pkts,connection.resp_ip_bytes,connection.orig_p,connection.duration,connection.resp_bytes,connection.orig_pkts,...,connection.service,connection.orig_bytes,connection.conn_state,connection.resp_p,connection.orig_ip_bytes,dns_count,ssh_count,http_count,ssl_count,files_count
count,21876,21876,21876,21876,2.187600e+04,2.187600e+04,21876.00000,21876.000000,2.187600e+04,2.187600e+04,...,21876,21876.000000,21876,21876.000000,2.187600e+04,21876.000000,21876.000000,21876.000000,21876.000000,21876.00000
unique,16,1201,21876,21833,NaN,NaN,NaN,NaN,NaN,NaN,...,15,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,192.168.10.15,192.168.10.3,C56EKp1Gi60BjQUeKh,2017-07-06T12:20:13.236729Z,NaN,NaN,NaN,NaN,NaN,NaN,...,dns,NaN,SF,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,6115,10156,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,14043,NaN,20487,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,7.547312e+01,1.573343e+05,46550.96855,14.418953,1.542137e+05,5.779964e+01,...,NaN,587.893811,NaN,234.507223,3.023709e+03,0.640976,0.001554,0.079219,0.130234,0.37036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40%,NaN,NaN,NaN,NaN,2.000000e+00,1.920000e+02,50225.00000,0.030804,1.450000e+02,2.000000e+00,...,NaN,68.000000,NaN,53.000000,1.260000e+02,1.000000,0.000000,0.000000,0.000000,0.00000
50%,NaN,NaN,NaN,NaN,2.000000e+00,2.380000e+02,52424.00000,0.038096,1.820000e+02,2.000000e+00,...,NaN,76.000000,NaN,53.000000,1.360000e+02,1.000000,0.000000,0.000000,0.000000,0.00000
60%,NaN,NaN,NaN,NaN,2.000000e+00,2.900000e+02,56893.00000,0.063003,2.240000e+02,2.000000e+00,...,NaN,88.000000,NaN,53.000000,1.500000e+02,1.000000,0.000000,0.000000,0.000000,0.00000
80%,NaN,NaN,NaN,NaN,7.000000e+00,9.630000e+02,61109.00000,5.201623,5.580000e+02,9.000000e+00,...,NaN,432.000000,NaN,123.000000,8.990000e+02,1.000000,0.000000,0.000000,0.000000,0.00000
max,NaN,NaN,NaN,NaN,1.407985e+06,3.124255e+09,65533.00000,1296.738136,3.067928e+09,1.042889e+06,...,NaN,223623.000000,NaN,65529.000000,4.287491e+07,1.000000,1.000000,1.000000,1.000000,76.00000

### 1.1 Show distinct counts

In [8]:
distinct_counter = raw_data.apply(lambda x: len(x.unique()))
distinct_counter

originated_ip              16
responded_ip             1201
connection.uid          21876
connection.ts           21833
connection.resp_pkts      222
                        ...
dns_count                   2
ssh_count                   2
http_count                  2
ssl_count                   2
files_count                27
Length: 21, dtype: int64

### 1.2 Visualize frequencies

#### Get Frequency Counts of Categorical Columns: 

- connection.proto
- connection.service
- connection.conn_state

(https://cmdlinetips.com/2018/02/how-to-get-frequency-counts-of-a-column-in-pandas-dataframe/)

In [9]:
pd.reset_option('display.max_rows')

In [10]:
raw_data['connection.proto'].value_counts()

udp     15884
tcp      5986
icmp        6
Name: connection.proto, dtype: int64

In [11]:
raw_data['connection.service'].value_counts(dropna=False) # display null values as well

dns                   14043
ssl                    2849
http                   1732
ntp                    1593
none                   1279
krb                     120
krb_tcp                 110
dce_rpc                  34
ssh                      32
ftp                      30
ftp-data                 30
krb,smb,gssapi           11
smb,gssapi,dce_rpc        9
ntlm,gssapi,smb           2
smb,gssapi                2
Name: connection.service, dtype: int64

In [12]:
raw_data['connection.conn_state'].value_counts()

SF       20487
RSTR       430
S1         397
S0         350
RSTO       119
REJ         52
SHR         22
RSTRH       11
OTH          7
S3           1
Name: connection.conn_state, dtype: int64

#### Get Frequency Counts of Non-categorical Columns: 

- originated_ip
- responded_ip
- connection.duration
- connection.orig_pkts
- connection.orig_ip_bytes
- connection.resp_p
- connection.orig_bytes
- connection.resp_bytes
- connection.resp_ip_bytes
- connection.orig_p
- connection.resp_pkts

In [13]:
raw_data['originated_ip'].value_counts()

192.168.10.15    6115
192.168.10.3     4353
192.168.10.17    3148
192.168.10.19    1345
192.168.10.14    1225
192.168.10.5      943
192.168.10.16     859
192.168.10.12     812
192.168.10.9      744
192.168.10.51     698
192.168.10.50     525
192.168.10.25     477
192.168.10.8      326
172.16.0.1        304
188.92.40.81        1
192.168.10.1        1
Name: originated_ip, dtype: int64

In [14]:
# or print relative frequencies of unique values:
# (sometimes percentage is a better criterion then the count)

raw_data['originated_ip'].value_counts(normalize=True)

192.168.10.15    0.279530
192.168.10.3     0.198985
192.168.10.17    0.143902
192.168.10.19    0.061483
192.168.10.14    0.055997
192.168.10.5     0.043107
192.168.10.16    0.039267
192.168.10.12    0.037118
192.168.10.9     0.034010
192.168.10.51    0.031907
192.168.10.50    0.023999
192.168.10.25    0.021805
192.168.10.8     0.014902
172.16.0.1       0.013897
188.92.40.81     0.000046
192.168.10.1     0.000046
Name: originated_ip, dtype: float64

In [15]:
raw_data['responded_ip'].value_counts()

192.168.10.3       10156
192.168.10.1        4310
192.168.10.50        426
23.50.75.27          140
72.21.91.29          126
                   ...
17.253.14.125          1
173.194.207.127        1
64.34.226.87           1
52.84.26.13            1
162.159.210.8          1
Name: responded_ip, Length: 1201, dtype: int64

In [16]:
raw_data['connection.duration'].value_counts()

0.000000      87
0.000162      79
0.000172      75
0.000175      74
0.000168      72
              ..
0.195187       1
183.846499     1
0.060324       1
0.088434       1
11.051331      1
Name: connection.duration, Length: 14489, dtype: int64

In [17]:
pd.set_option('display.max_rows', None)
raw_data['connection.duration'].value_counts().nlargest(100)

0.000000    87
0.000162    79
0.000172    75
0.000175    74
0.000168    72
0.000179    71
0.000161    70
0.000182    69
0.000188    68
0.000198    67
0.000165    66
0.000166    66
0.000187    66
0.000171    66
0.000183    65
0.000185    65
0.000176    65
0.000177    65
0.000180    65
0.000167    64
0.000186    64
0.000174    64
0.000164    64
0.000157    63
0.000169    62
0.000200    61
0.000173    61
0.000159    61
0.000154    60
0.000163    59
0.000181    59
0.000191    58
0.000156    57
0.000184    56
0.000158    56
0.000178    55
0.000160    55
0.000197    55
0.000193    54
0.000155    54
0.000170    53
0.000152    53
0.000189    52
0.000203    51
0.000195    51
0.000207    50
0.000199    49
0.000192    48
0.000206    48
0.000201    48
0.000190    46
0.000196    46
0.000153    45
0.000204    43
0.000202    43
0.000194    43
0.000211    40
0.000212    39
0.000217    37
0.000151    36
0.000150    36
0.000205    34
0.000216    32
0.000208    32
0.000214    32
0.000149    31
0.000219    31
0.000148    31
0.000213    30
0.000145    30
0.000220    29
0.000210    29
0.000142    28
0.000144    28
0.000209    27
0.000218    26
0.000215    26
0.000223    24
0.000230    23
0.000221    22
0.000244    22
0.000236    22
0.000146    21
0.000227    21
0.000225    21
0.000139    21
0.000237    20
0.000147    20
0.000239    20
0.000224    20
0.000222    19
0.000229    19
0.000143    19
0.000001    19
0.000231    19
0.000226    18
0.000234    18
0.000247    18
0.000228    17
0.000141    16
Name: connection.duration, dtype: int64

In [18]:
# raw_data['connection.orig_pkts'].value_counts()
raw_data['connection.orig_pkts'].value_counts().nlargest(40)

2     8891
1     5668
4     1937
10     433
17     426
9      383
8      275
5      249
11     243
6      219
22     186
19     186
12     178
13     174
21     174
14     170
7      164
23     141
18     137
15     133
16     129
20     108
25      90
26      79
24      76
3       56
28      48
27      43
38      33
29      33
36      32
39      32
30      28
44      28
0       28
33      25
31      25
52      25
35      25
32      24
Name: connection.orig_pkts, dtype: int64

In [19]:
# raw_data['connection.orig_ip_bytes'].value_counts()
# raw_data['connection.orig_ip_bytes'].value_counts().nlargest(40)

In [20]:
# raw_data['connection.resp_p'].value_counts()
pd.set_option('display.max_rows', 30)
raw_data['connection.resp_p'].value_counts()

53       13866
443       2984
80        2614
123       1593
88         238
         ...
17969        1
42           1
37073        1
15965        1
26227        1
Name: connection.resp_p, Length: 59, dtype: int64

In [21]:
pd.set_option('display.max_rows', None)
raw_data['connection.resp_p'].value_counts().nlargest(40)

53       13866
443       2984
80        2614
123       1593
88         238
389        109
137        105
138         53
5353        47
465         34
22          34
21          30
5355        25
3268        17
445         15
49666       14
135         14
139          9
8612         9
49671        6
3289         6
1124         6
3            5
7725         4
8610         4
1900         2
27579        1
11348        1
25911        1
34299        1
23511        1
18484        1
8745         1
54481        1
25217        1
49829        1
53012        1
1            1
19302        1
11690        1
Name: connection.resp_p, dtype: int64

In [22]:
# raw_data['connection.orig_bytes'].value_counts()
raw_data['connection.orig_bytes'].value_counts().nlargest(40)

48     1513
0      1078
64      841
70      602
72      561
78      476
88      476
76      471
60      444
66      432
80      428
46      413
68      412
82      361
90      354
62      349
50      337
58      323
74      315
84      303
56      289
51      288
47      281
96      278
49      228
86      225
44      224
94      211
102     197
52      186
45      175
42      172
43      168
54      159
92      143
53      135
40      111
136     103
41      100
55       95
Name: connection.orig_bytes, dtype: int64

In [23]:
# raw_data['connection.resp_bytes'].value_counts()
raw_data['connection.resp_bytes'].value_counts().nlargest(40)

0      1356
48     1339
96      417
188     291
112     288
180     280
158     244
122     244
136     240
114     230
134     227
110     221
204     184
224     177
264     173
120     160
248     156
266     153
102     150
108     150
254     145
46      141
172     138
182     129
196     129
206     119
72      119
328     118
78      118
154     116
66      111
98      109
79      108
132     107
67      106
278     101
198      99
202      98
178      98
166      98
Name: connection.resp_bytes, dtype: int64

In [24]:
# raw_data['connection.resp_ip_bytes'].value_counts()
raw_data['connection.resp_ip_bytes'].value_counts().nlargest(40)

76     1331
152     442
112     374
92      364
0       356
244     284
236     284
214     254
178     246
190     228
168     228
166     218
192     218
260     181
170     180
320     172
102     171
280     169
158     157
304     155
322     152
176     148
310     146
164     138
228     136
150     125
262     120
100     118
106     116
220     116
238     116
384     115
252     110
94      109
107     108
258     108
95      106
366     104
334     102
154     100
Name: connection.resp_ip_bytes, dtype: int64

In [25]:
pd.set_option('display.max_rows', 30)
raw_data['connection.orig_p'].value_counts()

123      1593
137        85
138        53
5353       47
8612        9
         ...
1122        1
48017       1
35735       1
23453       1
8188        1
Name: connection.orig_p, Length: 13308, dtype: int64

In [26]:
# raw_data['connection.orig_p'].value_counts().nlargest(40)

In [27]:
# raw_data['connection.resp_pkts'].value_counts()
pd.set_option('display.max_rows', 30)
raw_data['connection.resp_pkts'].value_counts().nlargest(40)

2     10550
1      5631
15      442
0       356
10      352
      ...
35       21
39       21
32       20
38       18
37       18
Name: connection.resp_pkts, Length: 40, dtype: int64

### 1.3 Application data counts

In [28]:
raw_data['dns_count'].value_counts()

1    14022
0     7854
Name: dns_count, dtype: int64

In [29]:
raw_data['ssh_count'].value_counts()

0    21842
1       34
Name: ssh_count, dtype: int64

In [30]:
raw_data['http_count'].value_counts()

0    20143
1     1733
Name: http_count, dtype: int64

In [31]:
raw_data['ssl_count'].value_counts()

0    19027
1     2849
Name: ssl_count, dtype: int64

In [32]:
raw_data['files_count'].value_counts()

0     19134
2      1109
3       679
1       595
4       209
6        32
5        26
8        20
10       14
76       14
14        7
7         6
12        5
11        4
18        3
16        3
9         3
13        2
31        2
24        2
21        1
28        1
36        1
19        1
32        1
15        1
70        1
Name: files_count, dtype: int64